### ISSUE TITLE
Error while trying to run embedded_motif_interaction_example.py

### ISSUE THREAD

**Issue by anushree-a** [kundajelab/dfim#4]
Tried running the embedded motif interaction code for my own dataset (simulated as per the guidelines in the supplementary paper) and encountered the following error:

**Traceback (most recent call last):
  File "embedded_motif_interaction_example.py", line 162, in <module>
    reference_gc=0)
  File "build/bdist.linux-x86_64/egg/dfim/core.py", line 467, in compute_importance
  AttributeError: 'module' object has no attribute 'blobs'**

I am using the following software versions - 
Tensorflow version = _1.9.0_
Keras version = _2.2.4_
Deeplift version = _0.6.6.2_

Please let me know how to work around it. Thank you in advance for your time!

**Comment by pgreenside** [comment]
Thanks for letting me know. I wrote this example with Deeplift 0.4.0 and the structure of the Deeplift code base has changed since then. I would use the older, compatible version of Deeplift or otherwise you can update compute_importance() to respect the new structure (i.e. using deeplift.layers instead of deeplift.blobs). I will try to update the example soon.
